### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by newtreeaa** [vb000/NeuriCam#4]
hello,do you provide the dataset?

**Comment by newtreeaa** [comment]
How long does it take you to train once？Under the condition that the effect will not be greatly reduced, how much can the training epoch be reduced？

**Comment by vb000** [comment]
Hi @newtreeaa, we trained with [vimeo-90k](http://toflow.csail.mit.edu/) dataset. And, we used Matlab's imresize function for 4x downsampling to generate low-resolution grayscale inputs using this [script](https://github.com/xinntao/EDVR/blob/master/scripts/matlab_scripts/generate_LR_Vimeo90K.m).
