### ISSUE TITLE
Some Doubts

### ISSUE THREAD

**Issue by Pepe-77777** [vb000/NeuriCam#7]
I was looking, and I wanted to know what the "lr-set", "key-set" and "hr-set" folders would be

**Comment by vb000** [comment]
@Pepe-77777 `lr-set` would contain low-resolution grayscale frames. `key-set` would contain high-resolution color key-frames frames (4x upscaled relative to `lr-set`). And, `hr-set` would contain the complete high-resolution color ground-truth frames for performance measurement.

**Comment by Pepe-77777** [comment]
Thanks! I created a google colab for run this and I needed to know what it was.
